---
- name: Configure backup server
  hosts: backupServer
  become: true

  tasks:
    - name: Update package cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Update apt cache & install MongoDB tools
      apt:
        update_cache: yes
        name: mongo-tools
        state: present
      become: true

    - name: Copy mongo_ip.txt file to the server
      copy:
        src: "/Users/ayogun/Desktop/turbit/Working_Solution/1/mongo_ip.txt"
        dest: "/home/vagrant/Desktop/"
        owner: vagrant
        group: vagrant
        mode: 0600
        
    - name: Expose ip
      shell: cat /home/vagrant/Desktop/mongo_ip.txt
      register: ip_address_result

    - name: Set IP address as environment variable
      set_fact:
        mongo_ip: "{{ ip_address_result.stdout }}"

    - name: Create backup script
      copy:
        dest: /usr/local/bin/backup.sh
        content: |
          #!/bin/bash
          TIMESTAMP=$(date "+%Y%m%d-%H%M%S")
          mongodump --host {{ mongo_ip }} --out /var/backups/mongodb/$TIMESTAMP
        mode: '0755'   #Set the file mode to be executable
        owner: root

    - name: Configure backup cron job
      cron:
        name: "mongodb backup"
        job: "sh /usr/local/bin/backup.sh > /dev/null 2>&1"
        user: root
        hour: "*" # Run every hour
        #minute: "*" # Run every minute 

    - name: Restart cron service
      service:
        name: cron
        state: restarted



######### Client #########

 
    - name: Install WireGuard and OpenResolv
      apt:
        name:
          - wireguard
          - openresolv
        state: present
        update_cache: yes
      become: true

    - name: Copy mongo.conf file to the server
      copy:
        src: "/Users/ayogun/Desktop/turbit/Working_Solution/vpn/home/vagrant/algo/configs/172.16.13.149/wireguard/phone.conf"
        dest: "/home/vagrant/"
        owner: vagrant
        group: vagrant
        mode: 0600
      

    - name: Install WireGuard configuration file
      become: true
      shell: sudo install -o root -g root -m 600 /home/vagrant/phone.conf /etc/wireguard/wg0.conf


    - name: Start WireGuard VPN
      systemd:
        name: "wg-quick@wg0"
        state: started
        enabled: yes

