---
- name: Configure backup server
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: reboot if kernel updated
      command: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: true
      register: reboot
      when: reboot_required.stat.exists
      changed_when: reboot.rc == 1

      # - name: Reboot the machine
      #   become: true
      #   reboot:
      #     reboot_timeout: 300
      #     pre_reboot_delay: 0
      #     post_reboot_delay: 30

      - name: Get mongo_ip
        debug:
          var: mongo_ip

    - name: Update apt cache & install MongoDB tools
      apt:
        update_cache: yes
        name: mongo-tools
        state: present
      become: true

    - name: Create backup script
      copy:
        dest: /usr/local/bin/backup.sh
        user: root
        content: |
          #!/bin/bash
          TIMESTAMP=$(date "+%Y%m%d-%H%M%S")
          mongodump --host {{ mongo_ip }} --out /var/backups/mongodb/$TIMESTAMP
      mode: '0755'   #Set the file mode to be executable

    - name: Configure backup cron job
      cron:
        name: "mongodb backup"
        job: "sh /usr/local/bin/backup.sh > /dev/null 2>&1"
        user: root
        hour: "*" # Run every hour
        #minute: "*" # Run every minute 

######### Client #########

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      changed_when: false

    - name: Reboot the system
      command: sudo reboot
      when: reboot_required.stat.exists

    - name: Install WireGuard and OpenResolv
      apt:
        name:
          - wireguard
          - openresolv
        state: present
        update_cache: yes
      become: true

    - name: Copy file from VPN server
      fetch:
        src: "/home/vagrant/algo/configs/{{ vpn_ip }}/wireguard/backup.conf"
        dest: "/home/vagrant/"
        flat: yes
        fail_on_missing: yes
      vars:
        vpn_server_ip: "<ip_address_of_vpnserver>"

    - name: Install WireGuard configuration file
      copy:
        src: "/home/vagrant/backup.conf"
        dest: "/etc/wireguard/wg0.conf"
        owner: root
        group: root
        mode: 0600

    - name: Start WireGuard VPN
      systemd:
        name: "wg-quick@wg0"
        state: started
        enabled: yes

  