Vagrant.configure("2") do |config|
	config.vm.define "backupServer" do |backup|
	  backup.vm.box = "klinvill/kali_arm"
	  backup.vm.hostname = "backup-vm"
	  backup.vm.network "private_network", ip: "172.16.16.20" #bug
	  backup.vm.network "public_network", bridge: "en0"
	  backup.ssh.username = "vagrant"
	  backup.ssh.password = "vagrant"	# This is not best practice, but it's a lab. 
	  backup.ssh.host = "192.168.33.20"

	  backup.vm.provider "vmware_desktop" do |v|
		v.vmx["numvcpus"] = "2"
		v.vmx["memsize"] = "2048"
		v.gui = true
	  end
  
	  backup.vm.provision "ansible" do |ansible|
		ansible.playbook = "backup.yml"
		ansible.groups = {
			"backupgroup" => ["backup-vm"]
		}
	  end
	end
  end
  