---
- name: Install and configure MongoDB
  hosts: all
  become: true
  
  tasks:
    - name: Install MongoDB   # Default port is 27017
      apt:
        update_cache: yes # Run the equivalent of apt-get update before the operation. Can be run as part of the package installation or as a separate step.
        name: mongodb
        state: started
        

    - name: Start MongoDB service
      service:
        name: mongodb
        state: started
        enabled: yes  # Whether the service should start on boot.

    -name: Mongodb.conf file update
     lineinfile:
       path: /etc/mongodb.conf
       regexp: '^bindIp'
       line: 'bindIp: 192.168.33.10'
       state: present   # Thanks to this option I add the line if it doesn't exist at all

    - name: Install OpenVPN
  apt:
    name: openvpn
    state: present

- name: Copy OpenVPN client configuration
  copy:
    src: /path/to/client.ovpn  # Replace with the path to your client configuration file
    dest: /etc/openvpn/client.conf

- name: Install OpenVPN dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - resolvconf
    - ca-certificates

- name: Enable OpenVPN service
  systemd:
    name: openvpn@client
    enabled: yes
    state: started