  Vagrant.configure("2") do |config| 

	config.vm.define "vpn" do |vpn|
	  vpn.vm.box = "rshash/Ubuntu_22.04-M1-Mac"
	  vpn.vm.box_version = "0.1.0"
	  vpn.vm.hostname = "vpn-vm"
	  vpn.vm.network "private_network", ip: "172.16.15.28" # bug
	  vpn.vm.network "public_network", bridge: "en0"
	  vpn.ssh.username = "vagrant"
	  vpn.ssh.password = "vagrant"	# This is not best practice, but it's a lab.

	  vpn.vm.provider "vmware_desktop" do |v|
		v.vmx["numvcpus"] = "2"
		v.vmx["memsize"] = "2048"
		v.gui = true
	  end
	  vpn.vm.provision "ansible" do |ansible|
		ansible.playbook = "server.yml"
		# ansible.verbose = "vvv"
		ansible.groups = {
			"servergroup" => ["vpn-vm"]
		}
	  end
	end
end