# Vagrantfile for MongoDB VM

Vagrant.configure("2") do |config|
	  config.vm.box = "dummy"
	  config.vm.provider :aws do |aws , override|
		aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
		aws.secret_access_key = ENV["AWS_SECRET_ACCESS_KEY"]
		aws.region = "eu-central-1"
		aws.instance_type = "t2.micro"
		aws.iam_instance_profile_name = "turbitec2"
		aws.security_groups = ["default"]
		aws.keypair_name = "turbit"

		

		# Now I will override the ssh username and private key path
		override.ssh_username = "ubuntu"
		override.ssh_private_key_path = "/Users/ayogun/Downloads/turbit.pem"
	  end
	  config.vm.provision "ansible" do |ansible|
		ansible.playbook = "mongo-playbook.yml"
	  end
	end
  